# Generated by Django 2.2 on 2020-05-23 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0008_auto_20200523_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.Article')),
                ('claimed', models.BooleanField(default=False, verbose_name='Claimed')),
            ],
            bases=('article.article',),
        ),
        migrations.CreateModel(
            name='LostArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.Article')),
                ('found', models.BooleanField(default=False, verbose_name='Found')),
            ],
            bases=('article.article',),
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('lost', 'LOST'), ('found', 'FOUND'), ('request', 'REQUEST'), ('sell', 'SELL'), ('giveaway', 'GIVEAWAY')], default='LOST', max_length=15, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='SellArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.Article')),
                ('base_price', models.IntegerField(verbose_name='Baseprice')),
                ('claimed', models.BooleanField(default=False)),
                ('highest_claimed_price', models.IntegerField(default=None)),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('highest_claimant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hclaim')),
            ],
            bases=('article.article',),
        ),
        migrations.CreateModel(
            name='RequestArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.Article')),
                ('approvals', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='appprovals')),
            ],
            bases=('article.article',),
        ),
        migrations.CreateModel(
            name='GiveAwayArticle',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.Article')),
                ('deadline', models.DateTimeField()),
                ('approvals', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='appprovals')),
            ],
            bases=('article.article',),
        ),
    ]
