# Generated by Django 2.0 on 2020-05-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20200523_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('lost', 'lost'), ('found', 'found'), ('sell', 'sell'), ('give', 'give_away'), ('request', 'request')], default='REQ', max_length=10),
        ),
    ]
