# Generated by Django 2.0 on 2020-05-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
