# Generated by Django 2.0 on 2020-05-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200524_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
    ]
